services:
  - type: web
    name: nextjs-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: API_URL
        value: ''
    # Add other configurations like region, branch, etc.

  